apiVersion: v1
kind: Secret
metadata:
  name: twitter-connector.json
type: Opaque
stringData:
  twitter-connector.json: '{
      "name": "twitter_source",
      "config": {
        "connector.class": "com.github.jcustenborder.kafka.connect.twitter.TwitterSourceConnector",
        "twitter.oauth.consumerKey": "WOEH8PByLQbpGIF1qm9S1iL5I",
        "twitter.oauth.consumerSecret": "nWrpnNKxpqMoac61UTO50jdONd9TbBy973eud8cdAdPh5W1Blq",
        "twitter.oauth.accessToken": "933013635600977925-0uhqI5LSolzkVbFw2gs7pIqFYXOwHRb",
        "twitter.oauth.accessTokenSecret": "2vAyieLPGGX66QwqMXh5TLjHQiXnkgbLuocpWQ48cXFJp",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": false,
        "key.converter.schemas.enable": false,
        "kafka.status.topic": "twitter_json_01",
        "kafka.delete.topic": "twitter_json_01_deletes",
        "process.deletes": true,
        "filter.keywords": "gamussa",
        "tasks.max": "1"
      }
    }'
